site_name: COMP-5530 Group 12 Project Wiki

nav:
  - Home: index.md
  - Homeworks: homeworks.md
  - Project: project.md
  - OpenStack Notes: openstack.md
  - Processes: processes.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
